
# [[headers]]
#   for = "/*"
#   [headers.values]
#     Cache-Control = "public, max-age=120000"

# [[headers]]
#   for = "*.jpg"
#   [headers.values]
#     Cache-Control = "public, max-age=300"

# [[headers]]
#   for = "*.png"
#   [headers.values]
#     Cache-Control = "public, max-age=300"

# [[headers]]
#   for = "*.svg"
#   [headers.values]
#     Cache-Control = "public, max-age=30000"